// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/user.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export interface ValidateRequest {
  email: string;
  name: string;
  phone: string;
  surname: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  number: string;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  phone: string;
  surname: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  number: string;
}

export interface UpdateUserRequest {
  email: string;
  name: string;
  phone: string;
  surname: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  number: string;
  id: string;
}

export interface UserIdentity {
  email: string;
  id: string;
  phone: string;
}

export interface Empty {}

export interface UserInfo {
  email: string;
  name: string;
  phone: string;
  surname: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  number: string;
  id: string;
}

export interface UserList {
  users: UserInfo[];
}

export interface ValidateResponse {
  isValid: boolean;
  message: string;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserProxyServiceClient {
  validateUser(
    request: ValidateRequest,
    metadata?: Metadata,
  ): Observable<ValidateResponse>;

  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Observable<UserInfo>;

  getUser(request: UserIdentity, metadata?: Metadata): Observable<UserInfo>;

  getAllUsers(request: Empty, metadata?: Metadata): Observable<UserList>;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Observable<UserInfo>;

  deleteUser(
    request: UserIdentity,
    metadata?: Metadata,
  ): Observable<UserIdentity>;
}

export interface UserProxyServiceController {
  validateUser(
    request: ValidateRequest,
    metadata?: Metadata,
  ):
    | Promise<ValidateResponse>
    | Observable<ValidateResponse>
    | ValidateResponse;

  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<UserInfo> | Observable<UserInfo> | UserInfo;

  getUser(
    request: UserIdentity,
    metadata?: Metadata,
  ): Promise<UserInfo> | Observable<UserInfo> | UserInfo;

  getAllUsers(
    request: Empty,
    metadata?: Metadata,
  ): Promise<UserList> | Observable<UserList> | UserList;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserInfo> | Observable<UserInfo> | UserInfo;

  deleteUser(
    request: UserIdentity,
    metadata?: Metadata,
  ): Promise<UserIdentity> | Observable<UserIdentity> | UserIdentity;
}

export function UserProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'validateUser',
      'createUser',
      'getUser',
      'getAllUsers',
      'updateUser',
      'deleteUser',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('UserProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('UserProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USER_PROXY_SERVICE_NAME = 'UserProxyService';
